/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as metaDataFacetSol from "./MetaDataFacet.sol";
export type { metaDataFacetSol };
export type { FakeGotchisNFTFacet } from "./FakeGotchisNFTFacet";
