/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iFakeGotchisSol from "./IFakeGotchis.sol";
export type { iFakeGotchisSol };
export type { IDiamondCut } from "./IDiamondCut";
export type { IDiamondLoupe } from "./IDiamondLoupe";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155TokenReceiver } from "./IERC1155TokenReceiver";
export type { IERC165 } from "./IERC165";
export type { IERC173 } from "./IERC173";
export type { IERC20 } from "./IERC20";
export type { IERC2981 } from "./IERC2981";
export type { IERC721 } from "./IERC721";
export type { IERC721TokenReceiver } from "./IERC721TokenReceiver";
export type { IMultiRoyalty } from "./IMultiRoyalty";
export type { IRealmDiamond } from "./IRealmDiamond";
