/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as facets from "./facets";
export { FakeGotchisCardDiamond__factory } from "./FakeGotchisCardDiamond__factory";
