/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../common";

export type QueueItemStruct = {
  owner: PromiseOrValue<string>;
  installationType: PromiseOrValue<BigNumberish>;
  claimed: PromiseOrValue<boolean>;
  readyBlock: PromiseOrValue<BigNumberish>;
  id: PromiseOrValue<BigNumberish>;
};

export type QueueItemStructOutput = [
  string,
  number,
  boolean,
  number,
  BigNumber
] & {
  owner: string;
  installationType: number;
  claimed: boolean;
  readyBlock: number;
  id: BigNumber;
};

export type InstallationTypeStruct = {
  width: PromiseOrValue<BigNumberish>;
  height: PromiseOrValue<BigNumberish>;
  installationType: PromiseOrValue<BigNumberish>;
  level: PromiseOrValue<BigNumberish>;
  alchemicaType: PromiseOrValue<BigNumberish>;
  spillRadius: PromiseOrValue<BigNumberish>;
  spillRate: PromiseOrValue<BigNumberish>;
  upgradeQueueBoost: PromiseOrValue<BigNumberish>;
  craftTime: PromiseOrValue<BigNumberish>;
  nextLevelId: PromiseOrValue<BigNumberish>;
  deprecated: PromiseOrValue<boolean>;
  alchemicaCost: [
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>,
    PromiseOrValue<BigNumberish>
  ];
  harvestRate: PromiseOrValue<BigNumberish>;
  capacity: PromiseOrValue<BigNumberish>;
  prerequisites: PromiseOrValue<BigNumberish>[];
  name: PromiseOrValue<string>;
};

export type InstallationTypeStructOutput = [
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  boolean,
  [BigNumber, BigNumber, BigNumber, BigNumber],
  BigNumber,
  BigNumber,
  BigNumber[],
  string
] & {
  width: number;
  height: number;
  installationType: number;
  level: number;
  alchemicaType: number;
  spillRadius: number;
  spillRate: number;
  upgradeQueueBoost: number;
  craftTime: number;
  nextLevelId: number;
  deprecated: boolean;
  alchemicaCost: [BigNumber, BigNumber, BigNumber, BigNumber];
  harvestRate: BigNumber;
  capacity: BigNumber;
  prerequisites: BigNumber[];
  name: string;
};

export type ItemTypeIOStruct = {
  balance: PromiseOrValue<BigNumberish>;
  itemId: PromiseOrValue<BigNumberish>;
  installationType: InstallationTypeStruct;
};

export type ItemTypeIOStructOutput = [
  BigNumber,
  BigNumber,
  InstallationTypeStructOutput
] & {
  balance: BigNumber;
  itemId: BigNumber;
  installationType: InstallationTypeStructOutput;
};

export declare namespace InstallationFacet {
  export type BatchCraftInstallationsInputStruct = {
    installationID: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    gltr: PromiseOrValue<BigNumberish>;
  };

  export type BatchCraftInstallationsInputStructOutput = [
    number,
    number,
    number
  ] & { installationID: number; amount: number; gltr: number };

  export type ReservoirStatsStruct = {
    spillRate: PromiseOrValue<BigNumberish>;
    spillRadius: PromiseOrValue<BigNumberish>;
    capacity: PromiseOrValue<BigNumberish>;
  };

  export type ReservoirStatsStructOutput = [BigNumber, BigNumber, BigNumber] & {
    spillRate: BigNumber;
    spillRadius: BigNumber;
    capacity: BigNumber;
  };

  export type InstallationIdIOStruct = {
    installationId: PromiseOrValue<BigNumberish>;
    balance: PromiseOrValue<BigNumberish>;
  };

  export type InstallationIdIOStructOutput = [BigNumber, BigNumber] & {
    installationId: BigNumber;
    balance: BigNumber;
  };
}

export interface InstallationFacetInterface extends utils.Interface {
  functions: {
    "balanceOfToken(address,uint256,uint256)": FunctionFragment;
    "batchCraftInstallations((uint16,uint16,uint40)[])": FunctionFragment;
    "claimInstallations(uint256[])": FunctionFragment;
    "craftInstallations(uint16[],uint40[])": FunctionFragment;
    "equipInstallation(address,uint256,uint256)": FunctionFragment;
    "getAltarLevel(uint256)": FunctionFragment;
    "getCraftQueue(address)": FunctionFragment;
    "getInstallationType(uint256)": FunctionFragment;
    "getInstallationTypes(uint256[])": FunctionFragment;
    "getInstallationUnequipType(uint256)": FunctionFragment;
    "getLodgeLevel(uint256)": FunctionFragment;
    "getReservoirCapacity(uint256)": FunctionFragment;
    "getReservoirStats(uint256)": FunctionFragment;
    "installationBalancesOfToken(address,uint256)": FunctionFragment;
    "installationBalancesOfTokenByIds(address,uint256,uint256[])": FunctionFragment;
    "installationBalancesOfTokenWithTypes(address,uint256)": FunctionFragment;
    "installationsBalances(address)": FunctionFragment;
    "installationsBalancesWithTypes(address)": FunctionFragment;
    "reduceCraftTime(uint256[],uint40[])": FunctionFragment;
    "spilloverRateAndRadiusOfId(uint256)": FunctionFragment;
    "unequipInstallation(address,uint256,uint256)": FunctionFragment;
    "upgradeComplete(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "balanceOfToken"
      | "balanceOfToken(address,uint256,uint256)"
      | "batchCraftInstallations"
      | "batchCraftInstallations((uint16,uint16,uint40)[])"
      | "claimInstallations"
      | "claimInstallations(uint256[])"
      | "craftInstallations"
      | "craftInstallations(uint16[],uint40[])"
      | "equipInstallation"
      | "equipInstallation(address,uint256,uint256)"
      | "getAltarLevel"
      | "getAltarLevel(uint256)"
      | "getCraftQueue"
      | "getCraftQueue(address)"
      | "getInstallationType"
      | "getInstallationType(uint256)"
      | "getInstallationTypes"
      | "getInstallationTypes(uint256[])"
      | "getInstallationUnequipType"
      | "getInstallationUnequipType(uint256)"
      | "getLodgeLevel"
      | "getLodgeLevel(uint256)"
      | "getReservoirCapacity"
      | "getReservoirCapacity(uint256)"
      | "getReservoirStats"
      | "getReservoirStats(uint256)"
      | "installationBalancesOfToken"
      | "installationBalancesOfToken(address,uint256)"
      | "installationBalancesOfTokenByIds"
      | "installationBalancesOfTokenByIds(address,uint256,uint256[])"
      | "installationBalancesOfTokenWithTypes"
      | "installationBalancesOfTokenWithTypes(address,uint256)"
      | "installationsBalances"
      | "installationsBalances(address)"
      | "installationsBalancesWithTypes"
      | "installationsBalancesWithTypes(address)"
      | "reduceCraftTime"
      | "reduceCraftTime(uint256[],uint40[])"
      | "spilloverRateAndRadiusOfId"
      | "spilloverRateAndRadiusOfId(uint256)"
      | "unequipInstallation"
      | "unequipInstallation(address,uint256,uint256)"
      | "upgradeComplete"
      | "upgradeComplete(uint256)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "balanceOfToken",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfToken(address,uint256,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCraftInstallations",
    values: [InstallationFacet.BatchCraftInstallationsInputStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCraftInstallations((uint16,uint16,uint40)[])",
    values: [InstallationFacet.BatchCraftInstallationsInputStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimInstallations",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimInstallations(uint256[])",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "craftInstallations",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "craftInstallations(uint16[],uint40[])",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "equipInstallation",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "equipInstallation(address,uint256,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getAltarLevel",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAltarLevel(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCraftQueue",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCraftQueue(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationType(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationTypes",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationTypes(uint256[])",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationUnequipType",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationUnequipType(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLodgeLevel",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getLodgeLevel(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservoirCapacity",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservoirCapacity(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservoirStats",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservoirStats(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationBalancesOfToken",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationBalancesOfToken(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationBalancesOfTokenByIds",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "installationBalancesOfTokenByIds(address,uint256,uint256[])",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "installationBalancesOfTokenWithTypes",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationBalancesOfTokenWithTypes(address,uint256)",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationsBalances",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationsBalances(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationsBalancesWithTypes",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "installationsBalancesWithTypes(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceCraftTime",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "reduceCraftTime(uint256[],uint40[])",
    values: [PromiseOrValue<BigNumberish>[], PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "spilloverRateAndRadiusOfId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "spilloverRateAndRadiusOfId(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "unequipInstallation",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "unequipInstallation(address,uint256,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeComplete",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeComplete(uint256)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "balanceOfToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfToken(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCraftInstallations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchCraftInstallations((uint16,uint16,uint40)[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimInstallations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimInstallations(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "craftInstallations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "craftInstallations(uint16[],uint40[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "equipInstallation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "equipInstallation(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAltarLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAltarLevel(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCraftQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCraftQueue(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationType(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationTypes(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationUnequipType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationUnequipType(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLodgeLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLodgeLevel(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservoirCapacity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservoirCapacity(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservoirStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservoirStats(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationBalancesOfToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationBalancesOfToken(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationBalancesOfTokenByIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationBalancesOfTokenByIds(address,uint256,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationBalancesOfTokenWithTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationBalancesOfTokenWithTypes(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationsBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationsBalances(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationsBalancesWithTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "installationsBalancesWithTypes(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reduceCraftTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reduceCraftTime(uint256[],uint40[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spilloverRateAndRadiusOfId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spilloverRateAndRadiusOfId(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unequipInstallation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unequipInstallation(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeComplete(uint256)",
    data: BytesLike
  ): Result;

  events: {
    "AddedToQueue(uint256,uint256,uint256,address)": EventFragment;
    "CraftTimeReduced(uint256,uint256)": EventFragment;
    "QueueClaimed(uint256)": EventFragment;
    "UpgradeTimeReduced(uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddedToQueue"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "AddedToQueue(uint256,uint256,uint256,address)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CraftTimeReduced"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CraftTimeReduced(uint256,uint256)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QueueClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "QueueClaimed(uint256)"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpgradeTimeReduced"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "UpgradeTimeReduced(uint256,uint256,uint256,uint256,uint256)"
  ): EventFragment;
}

export interface AddedToQueueEventObject {
  _queueId: BigNumber;
  _installationId: BigNumber;
  _readyBlock: BigNumber;
  _sender: string;
}
export type AddedToQueueEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, string],
  AddedToQueueEventObject
>;

export type AddedToQueueEventFilter = TypedEventFilter<AddedToQueueEvent>;

export interface CraftTimeReducedEventObject {
  _queueId: BigNumber;
  _blocksReduced: BigNumber;
}
export type CraftTimeReducedEvent = TypedEvent<
  [BigNumber, BigNumber],
  CraftTimeReducedEventObject
>;

export type CraftTimeReducedEventFilter =
  TypedEventFilter<CraftTimeReducedEvent>;

export interface QueueClaimedEventObject {
  _queueId: BigNumber;
}
export type QueueClaimedEvent = TypedEvent<
  [BigNumber],
  QueueClaimedEventObject
>;

export type QueueClaimedEventFilter = TypedEventFilter<QueueClaimedEvent>;

export interface UpgradeTimeReducedEventObject {
  _queueId: BigNumber;
  _realmId: BigNumber;
  _coordinateX: BigNumber;
  _coordinateY: BigNumber;
  _blocksReduced: BigNumber;
}
export type UpgradeTimeReducedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  UpgradeTimeReducedEventObject
>;

export type UpgradeTimeReducedEventFilter =
  TypedEventFilter<UpgradeTimeReducedEvent>;

export interface InstallationFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: InstallationFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    balanceOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    "balanceOfToken(address,uint256,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    batchCraftInstallations(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "batchCraftInstallations((uint16,uint16,uint40)[])"(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    claimInstallations(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "claimInstallations(uint256[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    craftInstallations(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "craftInstallations(uint16[],uint40[])"(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    equipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "equipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAltarLevel(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { altarLevel_: BigNumber }>;

    "getAltarLevel(uint256)"(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { altarLevel_: BigNumber }>;

    getCraftQueue(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [QueueItemStructOutput[]] & { output_: QueueItemStructOutput[] }
    >;

    "getCraftQueue(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [QueueItemStructOutput[]] & { output_: QueueItemStructOutput[] }
    >;

    getInstallationType(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationTypeStructOutput] & {
        installationType: InstallationTypeStructOutput;
      }
    >;

    "getInstallationType(uint256)"(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationTypeStructOutput] & {
        installationType: InstallationTypeStructOutput;
      }
    >;

    getInstallationTypes(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [InstallationTypeStructOutput[]] & {
        installationTypes_: InstallationTypeStructOutput[];
      }
    >;

    "getInstallationTypes(uint256[])"(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [InstallationTypeStructOutput[]] & {
        installationTypes_: InstallationTypeStructOutput[];
      }
    >;

    getInstallationUnequipType(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getInstallationUnequipType(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getLodgeLevel(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { lodgeLevel_: BigNumber }>;

    "getLodgeLevel(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { lodgeLevel_: BigNumber }>;

    getReservoirCapacity(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { capacity_: BigNumber }>;

    "getReservoirCapacity(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { capacity_: BigNumber }>;

    getReservoirStats(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationFacet.ReservoirStatsStructOutput] & {
        reservoirStats_: InstallationFacet.ReservoirStatsStructOutput;
      }
    >;

    "getReservoirStats(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationFacet.ReservoirStatsStructOutput] & {
        reservoirStats_: InstallationFacet.ReservoirStatsStructOutput;
      }
    >;

    installationBalancesOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationFacet.InstallationIdIOStructOutput[]] & {
        bals_: InstallationFacet.InstallationIdIOStructOutput[];
      }
    >;

    "installationBalancesOfToken(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationFacet.InstallationIdIOStructOutput[]] & {
        bals_: InstallationFacet.InstallationIdIOStructOutput[];
      }
    >;

    installationBalancesOfTokenByIds(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    "installationBalancesOfTokenByIds(address,uint256,uint256[])"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    installationBalancesOfTokenWithTypes(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [ItemTypeIOStructOutput[]] & {
        installationBalancesOfTokenWithTypes_: ItemTypeIOStructOutput[];
      }
    >;

    "installationBalancesOfTokenWithTypes(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [ItemTypeIOStructOutput[]] & {
        installationBalancesOfTokenWithTypes_: ItemTypeIOStructOutput[];
      }
    >;

    installationsBalances(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationFacet.InstallationIdIOStructOutput[]] & {
        bals_: InstallationFacet.InstallationIdIOStructOutput[];
      }
    >;

    "installationsBalances(address)"(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [InstallationFacet.InstallationIdIOStructOutput[]] & {
        bals_: InstallationFacet.InstallationIdIOStructOutput[];
      }
    >;

    installationsBalancesWithTypes(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ItemTypeIOStructOutput[]] & { output_: ItemTypeIOStructOutput[] }
    >;

    "installationsBalancesWithTypes(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [ItemTypeIOStructOutput[]] & { output_: ItemTypeIOStructOutput[] }
    >;

    reduceCraftTime(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "reduceCraftTime(uint256[],uint40[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    spilloverRateAndRadiusOfId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "spilloverRateAndRadiusOfId(uint256)"(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    unequipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "unequipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    upgradeComplete(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "upgradeComplete(uint256)"(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  balanceOfToken(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "balanceOfToken(address,uint256,uint256)"(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  batchCraftInstallations(
    _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "batchCraftInstallations((uint16,uint16,uint40)[])"(
    _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  claimInstallations(
    _queueIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "claimInstallations(uint256[])"(
    _queueIds: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  craftInstallations(
    _installationTypes: PromiseOrValue<BigNumberish>[],
    _gltr: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "craftInstallations(uint16[],uint40[])"(
    _installationTypes: PromiseOrValue<BigNumberish>[],
    _gltr: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  equipInstallation(
    _owner: PromiseOrValue<string>,
    _realmId: PromiseOrValue<BigNumberish>,
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "equipInstallation(address,uint256,uint256)"(
    _owner: PromiseOrValue<string>,
    _realmId: PromiseOrValue<BigNumberish>,
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAltarLevel(
    _altarId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getAltarLevel(uint256)"(
    _altarId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCraftQueue(
    _owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<QueueItemStructOutput[]>;

  "getCraftQueue(address)"(
    _owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<QueueItemStructOutput[]>;

  getInstallationType(
    _installationTypeId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InstallationTypeStructOutput>;

  "getInstallationType(uint256)"(
    _installationTypeId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InstallationTypeStructOutput>;

  getInstallationTypes(
    _installationTypeIds: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<InstallationTypeStructOutput[]>;

  "getInstallationTypes(uint256[])"(
    _installationTypeIds: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<InstallationTypeStructOutput[]>;

  getInstallationUnequipType(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getInstallationUnequipType(uint256)"(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getLodgeLevel(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getLodgeLevel(uint256)"(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getReservoirCapacity(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getReservoirCapacity(uint256)"(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getReservoirStats(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InstallationFacet.ReservoirStatsStructOutput>;

  "getReservoirStats(uint256)"(
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InstallationFacet.ReservoirStatsStructOutput>;

  installationBalancesOfToken(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

  "installationBalancesOfToken(address,uint256)"(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

  installationBalancesOfTokenByIds(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _ids: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "installationBalancesOfTokenByIds(address,uint256,uint256[])"(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _ids: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  installationBalancesOfTokenWithTypes(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ItemTypeIOStructOutput[]>;

  "installationBalancesOfTokenWithTypes(address,uint256)"(
    _tokenContract: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ItemTypeIOStructOutput[]>;

  installationsBalances(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

  "installationsBalances(address)"(
    _account: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

  installationsBalancesWithTypes(
    _owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ItemTypeIOStructOutput[]>;

  "installationsBalancesWithTypes(address)"(
    _owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<ItemTypeIOStructOutput[]>;

  reduceCraftTime(
    _queueIds: PromiseOrValue<BigNumberish>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "reduceCraftTime(uint256[],uint40[])"(
    _queueIds: PromiseOrValue<BigNumberish>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  spilloverRateAndRadiusOfId(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  "spilloverRateAndRadiusOfId(uint256)"(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  unequipInstallation(
    _owner: PromiseOrValue<string>,
    _realmId: PromiseOrValue<BigNumberish>,
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "unequipInstallation(address,uint256,uint256)"(
    _owner: PromiseOrValue<string>,
    _realmId: PromiseOrValue<BigNumberish>,
    _installationId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  upgradeComplete(
    _queueId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "upgradeComplete(uint256)"(
    _queueId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    balanceOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOfToken(address,uint256,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchCraftInstallations(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    "batchCraftInstallations((uint16,uint16,uint40)[])"(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    claimInstallations(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "claimInstallations(uint256[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    craftInstallations(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "craftInstallations(uint16[],uint40[])"(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    equipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "equipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAltarLevel(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAltarLevel(uint256)"(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCraftQueue(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<QueueItemStructOutput[]>;

    "getCraftQueue(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<QueueItemStructOutput[]>;

    getInstallationType(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InstallationTypeStructOutput>;

    "getInstallationType(uint256)"(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InstallationTypeStructOutput>;

    getInstallationTypes(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<InstallationTypeStructOutput[]>;

    "getInstallationTypes(uint256[])"(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<InstallationTypeStructOutput[]>;

    getInstallationUnequipType(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getInstallationUnequipType(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLodgeLevel(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLodgeLevel(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReservoirCapacity(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReservoirCapacity(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReservoirStats(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InstallationFacet.ReservoirStatsStructOutput>;

    "getReservoirStats(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InstallationFacet.ReservoirStatsStructOutput>;

    installationBalancesOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

    "installationBalancesOfToken(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

    installationBalancesOfTokenByIds(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "installationBalancesOfTokenByIds(address,uint256,uint256[])"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    installationBalancesOfTokenWithTypes(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ItemTypeIOStructOutput[]>;

    "installationBalancesOfTokenWithTypes(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ItemTypeIOStructOutput[]>;

    installationsBalances(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

    "installationsBalances(address)"(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<InstallationFacet.InstallationIdIOStructOutput[]>;

    installationsBalancesWithTypes(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ItemTypeIOStructOutput[]>;

    "installationsBalancesWithTypes(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<ItemTypeIOStructOutput[]>;

    reduceCraftTime(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    "reduceCraftTime(uint256[],uint40[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    spilloverRateAndRadiusOfId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "spilloverRateAndRadiusOfId(uint256)"(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    unequipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "unequipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeComplete(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "upgradeComplete(uint256)"(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AddedToQueue(uint256,uint256,uint256,address)"(
      _queueId?: PromiseOrValue<BigNumberish> | null,
      _installationId?: PromiseOrValue<BigNumberish> | null,
      _readyBlock?: null,
      _sender?: null
    ): AddedToQueueEventFilter;
    AddedToQueue(
      _queueId?: PromiseOrValue<BigNumberish> | null,
      _installationId?: PromiseOrValue<BigNumberish> | null,
      _readyBlock?: null,
      _sender?: null
    ): AddedToQueueEventFilter;

    "CraftTimeReduced(uint256,uint256)"(
      _queueId?: PromiseOrValue<BigNumberish> | null,
      _blocksReduced?: null
    ): CraftTimeReducedEventFilter;
    CraftTimeReduced(
      _queueId?: PromiseOrValue<BigNumberish> | null,
      _blocksReduced?: null
    ): CraftTimeReducedEventFilter;

    "QueueClaimed(uint256)"(
      _queueId?: PromiseOrValue<BigNumberish> | null
    ): QueueClaimedEventFilter;
    QueueClaimed(
      _queueId?: PromiseOrValue<BigNumberish> | null
    ): QueueClaimedEventFilter;

    "UpgradeTimeReduced(uint256,uint256,uint256,uint256,uint256)"(
      _queueId?: PromiseOrValue<BigNumberish> | null,
      _realmId?: PromiseOrValue<BigNumberish> | null,
      _coordinateX?: null,
      _coordinateY?: null,
      _blocksReduced?: null
    ): UpgradeTimeReducedEventFilter;
    UpgradeTimeReduced(
      _queueId?: PromiseOrValue<BigNumberish> | null,
      _realmId?: PromiseOrValue<BigNumberish> | null,
      _coordinateX?: null,
      _coordinateY?: null,
      _blocksReduced?: null
    ): UpgradeTimeReducedEventFilter;
  };

  estimateGas: {
    balanceOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "balanceOfToken(address,uint256,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchCraftInstallations(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "batchCraftInstallations((uint16,uint16,uint40)[])"(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    claimInstallations(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "claimInstallations(uint256[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    craftInstallations(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "craftInstallations(uint16[],uint40[])"(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    equipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "equipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAltarLevel(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAltarLevel(uint256)"(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCraftQueue(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getCraftQueue(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInstallationType(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getInstallationType(uint256)"(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInstallationTypes(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getInstallationTypes(uint256[])"(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInstallationUnequipType(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getInstallationUnequipType(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getLodgeLevel(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getLodgeLevel(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReservoirCapacity(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReservoirCapacity(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReservoirStats(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getReservoirStats(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    installationBalancesOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "installationBalancesOfToken(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    installationBalancesOfTokenByIds(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "installationBalancesOfTokenByIds(address,uint256,uint256[])"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    installationBalancesOfTokenWithTypes(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "installationBalancesOfTokenWithTypes(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    installationsBalances(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "installationsBalances(address)"(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    installationsBalancesWithTypes(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "installationsBalancesWithTypes(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    reduceCraftTime(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "reduceCraftTime(uint256[],uint40[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    spilloverRateAndRadiusOfId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "spilloverRateAndRadiusOfId(uint256)"(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unequipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "unequipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    upgradeComplete(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "upgradeComplete(uint256)"(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    balanceOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOfToken(address,uint256,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchCraftInstallations(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "batchCraftInstallations((uint16,uint16,uint40)[])"(
      _inputs: InstallationFacet.BatchCraftInstallationsInputStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    claimInstallations(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "claimInstallations(uint256[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    craftInstallations(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "craftInstallations(uint16[],uint40[])"(
      _installationTypes: PromiseOrValue<BigNumberish>[],
      _gltr: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    equipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "equipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAltarLevel(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAltarLevel(uint256)"(
      _altarId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCraftQueue(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getCraftQueue(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInstallationType(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getInstallationType(uint256)"(
      _installationTypeId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInstallationTypes(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getInstallationTypes(uint256[])"(
      _installationTypeIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInstallationUnequipType(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getInstallationUnequipType(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getLodgeLevel(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getLodgeLevel(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReservoirCapacity(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReservoirCapacity(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReservoirStats(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReservoirStats(uint256)"(
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    installationBalancesOfToken(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "installationBalancesOfToken(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    installationBalancesOfTokenByIds(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "installationBalancesOfTokenByIds(address,uint256,uint256[])"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _ids: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    installationBalancesOfTokenWithTypes(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "installationBalancesOfTokenWithTypes(address,uint256)"(
      _tokenContract: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    installationsBalances(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "installationsBalances(address)"(
      _account: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    installationsBalancesWithTypes(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "installationsBalancesWithTypes(address)"(
      _owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    reduceCraftTime(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "reduceCraftTime(uint256[],uint40[])"(
      _queueIds: PromiseOrValue<BigNumberish>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    spilloverRateAndRadiusOfId(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "spilloverRateAndRadiusOfId(uint256)"(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unequipInstallation(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "unequipInstallation(address,uint256,uint256)"(
      _owner: PromiseOrValue<string>,
      _realmId: PromiseOrValue<BigNumberish>,
      _installationId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    upgradeComplete(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "upgradeComplete(uint256)"(
      _queueId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
