/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155Metadata_URI } from "./IERC1155Metadata_URI";
export type { IERC1155TokenReceiver } from "./IERC1155TokenReceiver";
export type { IERC165 } from "./IERC165";
export type { IERC173 } from "./IERC173";
